import {
  Monitor,
  Grid2x2,
  Search,
  Folder,
  FolderOpen,
  FileText,
  Download,
  Image as ImageIcon,
  Film,
  Music,
  Settings,
  Calculator,
  Paintbrush,
  Terminal,
  Globe,
  Bot,
  Store,
  Calendar,
  Clock3,
  LayoutGrid,
  Bell,
  Volume2,
  Wifi,
  Bluetooth,
  BatteryFull,
  Lock,
  User,
  Trash2,
  Power,
  PowerOff,
  RotateCw,
  Moon,
  RefreshCw,
  Upload,
  Copy,
  ClipboardPaste,
  Pencil,
  Save,
  X,
  Minus,
  Square,
  CopyCheck,
  Pin,
  PinOff,
  House,
  CircleHelp,
  ChevronUp,
  Battery,
  Cloud,
  Gamepad2,
  Shield,
  History,
  File,
  Menu,
  ChevronLeft,
  ChevronRight,
  Plus,
  Play,
  Users,
  Trophy,
  ShieldCheck,
  ShieldAlert,
  UserCheck,
  HardDrive,
  Activity,
  AlertTriangle,
  FileJson,
  FileCode,
  List,
  Type,
  SquareTerminal,
  MousePointer2,
  Code,
  Brush,
  Eraser,
  Undo,
  Redo,
  Box,
  Maximize2,
  Video,
  MonitorPlay,
  ArrowLeft,
  ArrowRight,
  Home,
  Star,
  PenTool,
  Circle,
  Send,
  Mic,
  Cpu,
  Database,
  Network,
  Edit2,
  Minimize2,
  MoreHorizontal,
  TrendingUp,
  Sun,
  ChevronDown,
  MessageSquare,
} from 'lucide-react';

export const Icons = {
  // Desktop & Shell
  Desktop: Monitor,
  StartMenu: Grid2x2,
  Search: Search,
  Widgets: LayoutGrid,
  SystemTray: ChevronUp,
  NotificationCenter: Bell,
  Calendar: Calendar,
  Clock: Clock3,
  Volume: Volume2,
  Wifi: Wifi,
  Bluetooth: Bluetooth,
  Battery: Battery,
  BatteryFull: BatteryFull,
  Weather: Cloud,
  LockScreen: Lock,
  User: User,
  Power: Power,
  Shutdown: PowerOff,
  Restart: RotateCw,
  Sleep: Moon,
  Home: House,
  Help: CircleHelp,

  // File Explorer
  FileExplorer: Folder,
  Folder: Folder,
  FolderOpen: FolderOpen,
  File: FileText, // Default file
  Documents: FileText,
  Downloads: Download,
  Pictures: ImageIcon,
  Videos: Film,
  Music: Music,
  FileJson: FileJson,
  FileCode: FileCode,
  List: List,
  Type: Type,

  // Actions
  Upload: Upload,
  Download: Download,
  Copy: Copy,
  Paste: ClipboardPaste,
  Delete: Trash2,
  Trash: Trash2,
  Rename: Pencil,
  Save: Save,
  Refresh: RefreshCw,
  Open: FolderOpen,
  Undo: Undo,
  Redo: Redo,

  // Window Controls
  Close: X,
  Minimize: Minus,
  Maximize: Square,
  Restore: CopyCheck,
  Pin: Pin,
  Unpin: PinOff,

  // Applications
  Settings: Settings,
  Calculator: Calculator,
  Paint: Paintbrush,
  Terminal: SquareTerminal,
  Browser: Globe,
  Assistant: Bot,
  Store: Store,
  Photos: ImageIcon,
  Xbox: Gamepad2,
  Security: Shield,
  Timeline: History,
  Box: Box,
  Video: Video,
  MonitorPlay: MonitorPlay,

  // Miscellaneous App Specific
  Gamepad: Gamepad2,
  Play: Play,
  Users: Users,
  Trophy: Trophy,
  ShieldCheck: ShieldCheck,
  ShieldAlert: ShieldAlert,
  UserCheck: UserCheck,
  HardDrive: HardDrive,
  Activity: Activity,
  AlertTriangle: AlertTriangle,
  Menu: Menu,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Plus: Plus,
  Brush: Brush,
  Eraser: Eraser,
  MousePointer2: MousePointer2,
  Code: Code,
  Maximize2: Maximize2,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  Star: Star,
  PenTool: PenTool,
  Circle: Circle,
  Send: Send,
  Mic: Mic,
  Cpu: Cpu,
  Database: Database,
  Network: Network,
  Edit2: Edit2,
  Minimize2: Minimize2,
  MoreHorizontal: MoreHorizontal,
  TrendingUp: TrendingUp,
  Sun: Sun,
  ChevronDown: ChevronDown,
  MessageSquare: MessageSquare,
} as const;

export type IconName = keyof typeof Icons;
